apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Values.name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ lower .Values.name }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  selector:
    app: {{ lower .Values.name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
